name: Check Nix Format

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  nixfmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v15
      - run: nix shell nixpkgs#nixfmt-tree -c treefmt --ci
